# Generated by Django 4.2.1 on 2023-05-29 08:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер группы')),
            ],
            options={
                'verbose_name_plural': 'Группы',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Предметы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('description', models.TextField(verbose_name='Описание теста')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.studgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.subject')),
            ],
            options={
                'verbose_name_plural': 'Тесты',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Баллы')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время попытки')),
                ('time_taken', models.IntegerField(default=0, verbose_name='Использованное время (в минутах)')),
                ('correct_answers', models.PositiveIntegerField(verbose_name='Количество правильных ответов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Попытки тестов',
            },
        ),
        migrations.CreateModel(
            name='TestActivationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_attempts', models.PositiveIntegerField(verbose_name='Количество попыток')),
                ('shuffle_questions', models.BooleanField(verbose_name='Перемешивать вопросы')),
                ('shuffle_answers', models.BooleanField(verbose_name='Перемешивать ответы')),
                ('time_limit', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ограничение по времени (в минутах)')),
                ('activation_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время активации')),
                ('expiration_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'verbose_name_plural': 'Доступ к тесту',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images')),
                ('answer_type', models.CharField(choices=[('Письменный', 'Письменный'), ('Единственный верный', 'Единственный верный'), ('Несколько верных', 'Несколько верных')], default='Письменный', max_length=20)),
                ('points', models.PositiveIntegerField(default=1)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'order_with_respect_to': 'test',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ответ')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Верный')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
                'order_with_respect_to': 'question',
            },
        ),
    ]
